language: node_js
node_js:
- '0.11'
- '0.10'
notifications:
  email: false
deploy:
  provider: npm
  email: lin.w.clark@gmail.com
  api_key: jWMiGtjjBx4ys6wARA
  on:
    tags: true
    repo: linclark/omnifocus-github
    all_branches: true
